# Generated by Django 6.0 on 2025-12-28 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='vegetarian',
            new_name='vegeterian',
        ),
    ]
